const PDFDocument = require('pdfkit');

const formatDate = (value) => {
  if (!value) return 'N/A';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return 'N/A';
  return date.toLocaleDateString('en-GB');
};

const formatMoney = (value) => {
  const numericValue = Number(value);
  if (!Number.isFinite(numericValue)) {
    return 'BDT 0';
  }
  return `BDT ${numericValue.toLocaleString()}`;
};

const buildLine = (doc, label, value) => {
  doc
    .font('Helvetica-Bold')
    .text(`${label}: `, { continued: true })
    .font('Helvetica')
    .text(value || 'N/A');
};

const generateAgreementPdf = (agreementData) =>
  new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const {
      agreementId,
      completedDate,
      property,
      buyer,
      seller,
      deal,
    } = agreementData;

    doc
      .fontSize(22)
      .font('Helvetica-Bold')
      .text('Property Deal Agreement', { align: 'center' });

    doc
      .moveDown(0.35)
      .fontSize(11)
      .font('Helvetica')
      .text(`Agreement No: ${agreementId}`, { align: 'center' })
      .text(`Completed On: ${formatDate(completedDate)}`, { align: 'center' });

    doc.moveDown(1.2);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#cbd5e1');
    doc.moveDown(1);

    doc.fontSize(14).font('Helvetica-Bold').text('Property Information');
    doc.moveDown(0.4);
    buildLine(doc, 'Title', property.title);
    buildLine(doc, 'Type', property.type);
    buildLine(doc, 'Location', property.location);
    buildLine(doc, 'Current Status', property.status);
    buildLine(doc, 'Listed Price', formatMoney(property.listedPrice));

    doc.moveDown(1);
    doc.fontSize(14).font('Helvetica-Bold').text('Buyer Information');
    doc.moveDown(0.4);
    buildLine(doc, 'Name', buyer.name);
    buildLine(doc, 'Email', buyer.email);
    buildLine(doc, 'Phone', buyer.phone);

    doc.moveDown(1);
    doc.fontSize(14).font('Helvetica-Bold').text('Seller Information');
    doc.moveDown(0.4);
    buildLine(doc, 'Name', seller.name);
    buildLine(doc, 'Email', seller.email);
    buildLine(doc, 'Phone', seller.phone);

    doc.moveDown(1);
    doc.fontSize(14).font('Helvetica-Bold').text('Deal Information');
    doc.moveDown(0.4);
    buildLine(doc, 'Offer Amount', formatMoney(deal.offerAmount));
    buildLine(doc, 'Final Property Status', deal.finalStatus);
    buildLine(doc, 'Request Message', deal.message);

    doc.moveDown(1.4);
    doc
      .fontSize(11)
      .font('Helvetica')
      .text(
        'This document is auto-generated by SmartEstate for reference and record keeping.',
        { align: 'left' },
      );

    doc.moveDown(1.4);
    doc
      .font('Helvetica-Bold')
      .text('Buyer Signature: ____________________', { align: 'left' });
    doc.moveDown(1.2);
    doc
      .font('Helvetica-Bold')
      .text('Seller Signature: ____________________', { align: 'left' });

    doc.end();
  });

module.exports = {
  generateAgreementPdf,
};
